# Generated by Django 3.1.7 on 2021-03-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_auto_20210308_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
